### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by tejas17shah** [leeyeehoo/GenNAS#2]
Getting this issue while running: python do_explore.py --search_space=nasbench101 --config=CONF_NB101 (Just replicated the code). Here are the traceback lines for debug: 

[W python_anomaly_mode.cpp:104] Warning: Error detected in ReluBackward0. Traceback of forward call that caused the error:                                                                           
File "/export/hdd/scratch/tshah74/GenNAS/do_explore.py", line 96, in <module>
losses = evaluator.evaluate(task,model_builder,arch_info)
File "/export/hdd/scratch/tshah74/GenNAS/builder_evaluator.py", line 34, in evaluate
output = model_builder.learn(model,data)
File "/export/hdd/scratch/tshah74/GenNAS/builder_model.py", line 154, in learn
return model(x)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/export/hdd/scratch/tshah74/GenNAS/pynbs/model_nb101_tri_bn.py", line 66, in forward
x = layer(x)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/export/hdd/scratch/tshah74/GenNAS/pynbs/model_nb101_tri_bn.py", line 131, in forward vertex_output = self.vertex_op[t](vertex_input)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/export/hdd/scratch/tshah74/GenNAS/pynbs/base_ops.py", line 43, in forward
x = self.conv1x1(x)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/export/hdd/scratch/tshah74/GenNAS/pynbs/base_ops.py", line 22, in forward
return self.conv_bn_relu(x)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl 
return forward_call(*input, **kwargs)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward 
input = module(input)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 98, in forward  
return F.relu(input, inplace=self.inplace)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/nn/functional.py", line 1299, in relu 
result = torch.relu(input) 
(function _print_stack)  

Traceback (most recent call last):  File "/export/hdd/scratch/tshah74/GenNAS/do_explore.py", line 96, in <module> losses = evaluator.evaluate(task,model_builder,arch_info) 
File "/export/hdd/scratch/tshah74/GenNAS/builder_evaluator.py", line 37, in evaluate loss.backward()
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/usr/scratch/tshah74/miniconda/envs/genNAS-rep/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward Variable._execution_engine.run_backward( RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16, 64, 8, 8]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
![image](https://user-images.githubusercontent.com/50770400/140661590-6d5b4df4-80f2-4d4e-84e0-be5ca2cb29f7.png)

**Comment by leeyeehoo** [comment]
Hi Tejas,

Can you send me your environment settings? Like pytorch version, torchvision version etc.

Thanks!

**Comment by tejas17shah** [comment]
Hey, here are the environment settings: 

GPU-related: 
CUDA Version: 11.5
Driver Version: 495.29.05
NVIDIA RTX A6000

Python 3.9.7
Pytorch 1.10.0
Torchvision 0.11.1

Anything else you would need?
![image](https://user-images.githubusercontent.com/50770400/140777849-98957c16-24a3-47e8-b2d2-1cec382f2bd1.png)

**Comment by leeyeehoo** [comment]
Hi Tejas,

I tried:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
ca-certificates           2021.10.26           h06a4308_2
certifi                   2021.10.8        py39h06a4308_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-ng              9.3.0               hd4cf53a_17
ncurses                   6.3                  heee7806_1
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.21.4                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0
python                    3.9.7                h12debd9_1
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h27cfd23_0
scipy                     1.7.2                    pypi_0    pypi
setuptools                58.0.4           py39h06a4308_0
simplejson                3.17.5                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0
tk                        8.6.11               h1ccaba5_0
torch                     1.10.0+cu113             pypi_0    pypi
torchaudio                0.10.0+cu113             pypi_0    pypi
torchvision               0.11.1+cu113             pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
tzdata                    2021e                hda174b7_0
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h7b6447c_0
yacs                      0.1.8                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3

Can you please use the dev_1.0 branch and try it out? Seems like the problem is solved in the developed version.

**Comment by tejas17shah** [comment]
Hey, 

Thanks for your response. The issue is still there. I have attached a few screenshots and my package list file. As far as I could compare your package versions and mine, they look almost identical - with a few minor differences. I'm unable to figure out why it is failing? 

Thanks for your proactive response to this issue. 
[packageInfo.txt](https://github.com/leeyeehoo/GenNAS/files/7502018/packageInfo.txt)
![image](https://user-images.githubusercontent.com/50770400/140865600-d1d691eb-4756-4f39-9c64-a82638b1b5b2.png)
![image](https://user-images.githubusercontent.com/50770400/140865866-02e6609c-9bb3-4bb5-a40a-3889f79268e9.png)

**Comment by leeyeehoo** [comment]
Hi Tejes,

Please downgrade your PyTorch to 1.7:

conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 -c pytorch

I remembered I went through this error before. I was using torch==1.9 and it's because we use the model from:

https://github.com/romulus0914/NASBench-PyTorch

**Comment by tejas17shah** [comment]
Hey, I think this is working. At least it hasn't stopped at the point it was until now. Closing this for now. Thanks for your help.
